### ISSUE TITLE
Add support for arbitrary precision integers

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf-standard#174]
This is also being tracked in https://github.com/spacetelescope/asdf/issues/552.

The simplest way to do this would be to add a type definition where the integer value would be stored as a list of smaller integer words. For example:

```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "http://stsci.edu/schemas/asdf/core/bigint-1.0.0"
title: Arbitrary precision integer value.

tag: "tag:stsci.edu:asdf/core/bigint-1.0.0"
type: object
properties:
    words:
        type: list
        items:
            - number
        minLength: 1
    sign:
        type: string
        pattern: "^[+-]$"
...
```

Tag implementations would simply pack/unpack the words as required.

A slightly fancier implementation would be to use an `ndarray` instead of a list to store the subwords. This would be more efficient for very large integers.

However, if we really care about efficiency for cases where there are large integers and many of them, we could get even more sophisticated. We could design the type so that the same underlying array block is used for all large integers in the tree in order to avoid the overhead incurred by many separate blocks. Integers would then be described in terms of a source block, an offset, and the number of subwords.

This could be made even more efficient by making sure that all integers in the tree with the same value are stored only once in the underlying `ndarray`.

The first suggestion is by far the easiest to implement, but since we are defining a new part of the standard, it's worth making sure we do it right.

cc @perrygreenfield
