### ISSUE TITLE
incorrect remap_axes example in documentation

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf-standard#233]
One example in the [remap_axes](https://asdf-standard.readthedocs.io/en/1.5.0/generated/stsci.edu/asdf/transform/remap_axes-1.3.0.html) documentation is not correct - suggest removing it.
It claims the two examples below are equivalent:

```
!transform/remap_axes-1.3.0
  mapping: [0, 0, 1]
```

```
!transform/concatenate-1.2.0
  forward:
    - !transform/remap_axes-1.3.0
      mapping: [0]
    - !transform/remap_axes-1.3.0
      mapping: [1]
```
